// Mocks generated by Mockito 5.0.10 from annotations
// in glucose_levels_tracker/test/main_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:glucose_levels_tracker/models/glucose_measurment.dart' as _i4;
import 'package:glucose_levels_tracker/services/glucose_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [GlucoseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlucoseService extends _i1.Mock implements _i2.GlucoseService {
  MockGlucoseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.GlucoseMeasurement>> fetchMeasurements() =>
      (super.noSuchMethod(Invocation.method(#fetchMeasurements, []),
              returnValue: Future<List<_i4.GlucoseMeasurement>>.value(
                  <_i4.GlucoseMeasurement>[]))
          as _i3.Future<List<_i4.GlucoseMeasurement>>);
}
